### ISSUE TITLE
Economic viability lemna production

### ISSUE THREAD

**Issue by mike0074** [mauricebasement/SUSAL#3]
Calculation of cost factors vs. benefits of dried lemna production. Can it be done profitable?

-Production (incl possible high energy requirements for drying)
vs. competitors (soy meal?), actual real market?

**Comment by mike0074** [comment]
interesting
http://www.foodnavigator-usa.com/Suppliers2/Could-Lemna-water-lentil-be-the-next-big-plant-based-protein

**Comment by mauricebasement** [comment]
This leads to the conclusion, that it makes most sense, to use urea where it is produced, and to try to feed the duckweed back to the producer of the urea, or at least to something at the same place. This avoids the need to dry the duckweed, which massivley lower its energy consumption.

**Comment by mauricebasement** [comment]
Issue closed due to new business model.
