### ISSUE TITLE
Duckweed client

### ISSUE THREAD

**Issue by mike0074** [mauricebasement/SUSAL#7]
Look for a chicken/fish/anything farm who is ready to test lemna as a nutrition additive, and setup respective production & procedures to evaluate client acceptability/partner customer/price finding/advertising

**Comment by mauricebasement** [comment]
I have a friend, his father is a farmer. I reached out to him and I am waiting for a reply.
If this is not successful, we can simply create a letter, or try to reach out to farmers by calling.

**Comment by mauricebasement** [comment]
Issue closed due to new business model.
